[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 500
maxMessageSize = 500
fileWatcherType = "none"
runOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
base            = "light"
primaryColor    = "#ED1C24"
backgroundColor = "#F2F2F2"
secondaryBackgroundColor = "#FFFFFF"
textColor       = "#000000"
font            = "sans serif"
