[server]
headless = true
maxUploadSize = 500
maxMessageSize = 500

[browser]
gatherUsageStats = false

[theme]
base            = "light"
primaryColor    = "#ED1C24"
backgroundColor = "#F2F2F2"
secondaryBackgroundColor = "#FFFFFF"
textColor       = "#000000"
font            = "sans serif"
